import hashlib
import base64
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.primitives import serialization
from typing import List, Dict, Any
from quantum_ares_core.graph.models import EngineResult

class ReportEngine:
    def generate(self, session_id: str, scores: Dict[str, Any], 
                 engine_results: List[EngineResult], 
                 graph_metadata: Dict[str, Any]) -> bytes:
        """Generate PDF using ReportLab 4"""
        from io import BytesIO
        output = BytesIO()
        p = canvas.Canvas(output, pagesize=letter)
        w, h = letter
        
        # Page 1 - Cover
        p.setFont("Helvetica-Bold", 24)
        p.drawCentredString(w/2, h - 100, "QUANTUM-ARES Security Assessment Report")
        
        p.setFont("Helvetica", 12)
        p.drawCentredString(w/2, h - 140, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        p.drawCentredString(w/2, h - 160, f"Session ID: {session_id}")
        
        # Score Circle
        p.setFillColor(scores.get("color", "gray"))
        p.circle(w/2, h/2, 60, fill=1)
        p.setFillColor(colors.white)
        p.setFont("Helvetica-Bold", 32)
        p.drawCentredString(w/2, h/2 - 10, str(scores.get("security_index", 0)))
        
        p.setFillColor(colors.black)
        p.setFont("Helvetica-Oblique", 10)
        p.drawCentredString(w/2, 50, "CONFIDENTIAL - Generated by QUANTUM-ARES v7.45")
        p.showPage()
        
        # Page 2 - Executive Summary
        p.setFont("Helvetica-Bold", 18)
        p.drawString(50, h - 50, "Executive Summary")
        
        p.setFont("Helvetica-Bold", 12)
        p.drawString(50, h - 80, "Engine Scores:")
        y = h - 100
        for res in engine_results:
            p.setFont("Helvetica", 10)
            p.drawString(70, y, f"{res.engine_name.replace('_', ' ').title()}: {res.score}/100")
            y -= 20
            
        p.setFont("Helvetica-Bold", 12)
        p.drawString(50, y - 20, "Security Index Breakdown:")
        p.setFont("Helvetica", 10)
        p.drawString(70, y - 40, "Weighted average of Zero-Trust (35%), Quantum (20%), Attack Path (25%), Supply Chain (10%), Compliance (10%)")
        
        p.showPage()
        p.save()
        
        return output.getvalue()

    def sign_report(self, pdf_bytes: bytes, private_key_pem: bytes) -> Dict[str, str]:
        sha256_hash = hashlib.sha256(pdf_bytes).hexdigest()
        
        # Sign with RSA
        private_key = serialization.load_pem_private_key(private_key_pem, password=None)
        signature = private_key.sign(
            pdf_bytes,
            padding.PKCS1v15(),
            hashes.SHA256()
        )
        
        return {
            "sha256": sha256_hash,
            "signature": base64.b64encode(signature).decode('utf-8')
        }

    def anchor_blockchain(self, session_id: str, sha256_hash: str, demo_mode: bool = True) -> str:
        if demo_mode:
            return f"0xdemo_{sha256_hash[:40]}_polygon_amoy"
        # Real web3 logic would go here
        return "0xreal_tx_hash_placeholder"
